<a href="https://colab.research.google.com/github/galindojimenezjuanandres-alt/programacion-1/blob/main/parcal2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**JUAN ANDRES GALINDO JIMENEZ**

2260662



**SEGUNDO PARCIAL**

**parte II**

Instruccion 1

In [24]:
import numpy as np
import pandas as pd

In [18]:
np.random.seed(0)
dt = np.random.randint(124, 198, 50) # el minimo es 124 y el maximo es 196
dt

array([168, 171, 188, 191, 191, 133, 145, 160, 194, 136, 182, 189, 163,
       170, 161, 149, 196, 133, 144, 193, 171, 188, 173, 153, 143, 143,
       138, 163, 156, 189, 133, 181, 156, 155, 147, 159, 179, 152, 158,
       124, 124, 160, 177, 129, 162, 141, 128, 166, 182, 155])

In [22]:
dt[dt > 160 ]

array([168, 171, 188, 191, 191, 194, 182, 189, 163, 170, 161, 196, 193,
       171, 188, 173, 163, 189, 181, 179, 177, 162, 166, 182])

In [40]:
dt.std()

np.float64(20.544936115743948)

In [158]:
funcion = (lambda x: (x - x.mean()) / x.std())

In [159]:
funcion(dt)

array([ 0.34850437,  0.49452575,  1.32198026,  1.46800164,  1.46800164,
       -1.35507844, -0.77099291, -0.04088599,  1.61402303, -1.20905706,
        1.02993749,  1.37065406,  0.1051354 ,  0.44585196,  0.00778781,
       -0.57629773,  1.71137062, -1.35507844, -0.8196667 ,  1.56534923,
        0.49452575,  1.32198026,  0.59187334, -0.38160255, -0.8683405 ,
       -0.8683405 , -1.11170947,  0.1051354 , -0.23558117,  1.37065406,
       -1.35507844,  0.9812637 , -0.23558117, -0.28425496, -0.67364532,
       -0.08955978,  0.88391611, -0.43027634, -0.13823358, -1.79314259,
       -1.79314259, -0.04088599,  0.78656852, -1.54977362,  0.0564616 ,
       -0.96568808, -1.59844741,  0.25115678,  1.02993749, -0.28425496])

In [162]:
og.describe()

,0
count,37.000000
mean,151.378855
std,20.292826
min,114.459936
25%,135.459936
50%,150.459936
75%,167.459936
max,186.459936


In [161]:
og =pd.DataFrame({158.45993626, 161.45993626, 178.45993626, 181.45993626,
       181.45993626, 123.45993626, 135.45993626, 150.45993626,
       184.45993626, 126.45993626, 172.45993626, 179.45993626,
       153.45993626, 160.45993626, 151.45993626, 139.45993626,
       186.45993626, 123.45993626, 134.45993626, 183.45993626,
       161.45993626, 178.45993626, 163.45993626, 143.45993626,
       133.45993626, 133.45993626, 128.45993626, 153.45993626,
       146.45993626, 179.45993626, 123.45993626, 171.45993626,
       146.45993626, 145.45993626, 137.45993626, 149.45993626,
       169.45993626, 142.45993626, 148.45993626, 114.45993626,
       114.45993626, 150.45993626, 167.45993626, 119.45993626,
       152.45993626, 131.45993626, 118.45993626, 156.45993626,
       172.45993626, 145.45993626})
og

,0
0,128.459936
1,131.459936
2,133.459936
3,134.459936
4,135.459936
5,137.459936
6,139.459936
7,142.459936
8,143.459936
9,145.459936


In [166]:
from google.colab import files
import csv

dtos = [[
    ["arreglos"],
    [158.45993626, 161.45993626, 178.45993626, 181.45993626,
       181.45993626, 123.45993626, 135.45993626, 150.45993626,
       184.45993626, 126.45993626, 172.45993626, 179.45993626,
       153.45993626, 160.45993626, 151.45993626, 139.45993626,
       186.45993626, 123.45993626, 134.45993626, 183.45993626,
       161.45993626, 178.45993626, 163.45993626, 143.45993626,
       133.45993626, 133.45993626, 128.45993626, 153.45993626,
       146.45993626, 179.45993626, 123.45993626, 171.45993626,
       146.45993626, 145.45993626, 137.45993626, 149.45993626,
       169.45993626, 142.45993626, 148.45993626, 114.45993626,
       114.45993626, 150.45993626, 167.45993626, 119.45993626,
       152.45993626, 131.45993626, 118.45993626, 156.45993626,
       172.45993626, 145.45993626]
]]
with open("og.csv", "w", newline="") as f:
    writer = csv.writer(f)
    writer.writerows(og2)

files.download("og.csv")

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

instruccion 2

In [82]:
df = pd.DataFrame({"nombre": ["dani","maria","jose","juan","luna"],
                   "edad":[18, 317, 20,18,21],
                   "nota":[4.0, 5.0, 3.0,5.0,4.9],
                   "carrera":["derecho","matematicas","deportes","matematicas","idiomas"]})

df

,nombre,edad,nota,carrera
0,dani,18,4.0,derecho
1,maria,317,5.0,matematicas
2,jose,20,3.0,deportes
3,juan,18,5.0,matematicas
4,luna,21,4.9,idiomas


In [65]:
df.head(1)

,nombre,edad,nota,carrera
0,dani,18,4.0,derecho


In [66]:
df["nombre"]

,nombre
0,dani
1,maria
2,jose
3,juan
4,luna


In [67]:
df.loc[df["carrera"] == "matematicas"]

,nombre,edad,nota,carrera
1,maria,317,5.0,matematicas
3,juan,18,5.0,matematicas


In [70]:
calificaciones = df.groupby("carrera")["nota"].mean()
calificaciones

,nota
carrera,
deportes,3.0
derecho,4.0
idiomas,4.9
matematicas,5.0


In [130]:
  notas = [[({"nombre": ["dani","maria","jose","juan","luna"],
                   "edad":[18, 317, 20,18,21],
                   "nota":[4.0, 5.0, 3.0,5.0,4.9],
                   "carrera":["derecho","matematicas","deportes","matematicas","idiomas"]})]]


with open("notas.csv", "w", newline="") as f:
    writer = csv.writer(f)
    writer.writerows(notas)

files.download("notas.csv")

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

**parte III**

In [168]:
C = np.random.normal(loc = 7.2, scale=0.4, size = 56)
D = np.random.gamma(shape=306, scale=0.0229, size=56)
C



array([7.61213689, 6.99882378, 7.09759787, 7.41708338, 7.33425428,
       7.21613668, 7.86842474, 6.7988298 , 7.76097828, 6.99267145,
       6.56408461, 7.26714581, 6.82923635, 6.84953662, 7.94450089,
       7.31842428, 7.24641874, 7.30745165, 6.97127741, 7.39426224,
       6.70769752, 6.48091579, 6.74517183, 7.61532409, 6.79936604,
       6.65314361, 7.32970866, 7.7187372 , 7.72156298, 6.94818373,
       7.65003435, 7.60827513, 6.8923752 , 7.58619446, 7.96403454,
       8.05045492, 7.5534047 , 6.93247767, 7.56355708, 7.92482513,
       7.09740783, 7.26317279, 6.59296895, 7.2349383 , 7.57767726,
       6.77766956, 7.25106604, 6.01533987, 8.04411994, 7.43226802,
       6.90600317, 7.08565423, 6.82938331, 6.9971668 , 6.44892091,
       7.43168731])

In [169]:
D

array([7.6008748 , 7.61470193, 6.70078336, 7.44003625, 7.11099862,
       6.99686714, 6.45072868, 7.06993049, 6.85816102, 6.77802444,
       6.89367917, 6.87273608, 6.54854714, 6.58763058, 7.00197434,
       7.03217159, 6.91644633, 6.64525896, 6.79701234, 7.85816303,
       6.96098292, 7.78848838, 6.58879057, 7.40578451, 7.33751299,
       7.6201407 , 7.4240325 , 6.98173182, 7.23831252, 7.99806358,
       6.96213567, 7.37349636, 6.54019252, 7.4741896 , 6.6817842 ,
       7.8384223 , 7.68915623, 5.89585951, 7.04595001, 7.12637443,
       6.80144963, 7.49247892, 6.5172234 , 7.56950822, 6.8825487 ,
       6.41374178, 7.31617125, 6.99537395, 7.14816568, 7.01541853,
       6.83829488, 6.49623896, 7.67742352, 6.73147254, 7.05937601,
       7.41248143])

In [205]:
df2 = pd.DataFrame({"Grupo":"primer grupo ",
"NOTAs ":[ 6.72474307, 7.14023429, 7.07866843, 6.65612118, 6.34479306,
       7.36037484, 7.48273696, 7.51704311, 7.10663077, 7.54389813,
       7.34651221, 7.49056926, 7.20717538, 6.28580804, 6.60846195,
       6.65872002, 7.18842179, 6.51302701, 6.7388363 , 7.57641232,
       6.78858923, 7.22621432, 7.36418812, 6.73242786, 6.43423695,
       7.22929423, 7.49987525, 7.23445532, 6.50510603, 7.26197351,
       7.07756006, 7.56077633, 7.53295151, 7.03131765, 6.29958868,
       6.52571036, 7.51828246, 7.06296619, 7.34738676, 7.16102798,
       7.4555494 , 7.62455467, 6.89056529, 6.92159382, 7.03505742,
       6.47587721, 7.81233072, 7.18669956, 7.17120718, 7.22746119,
       7.66622784, 7.10060162, 7.00820683, 6.86341733, 7.1462615 ,
       6.89710013],
  "Grupo ":"segundo grupo  ",
  "NOTAS ":[7.06538673, 6.63020026, 6.93421015, 7.26596809, 6.77213648,
       6.99146168, 7.48559638, 6.8132169 , 7.30840413, 6.88707496,
       6.42811228, 7.34358513, 6.76847083, 6.7897076 , 6.45398014,
       8.29655884, 7.13091315, 7.15509533, 7.13761067, 6.77133049,
       7.34982674, 6.98266754, 6.75173262, 7.67988551, 6.95451266,
       7.54942964, 6.31856387, 6.50886172, 7.2053234 , 7.09441015,
       6.5513539 , 6.97878487, 6.91860334, 7.159794  , 7.22983809,
       6.85270613, 7.0559274 , 6.47430432, 6.19880285, 6.35867452,
       7.37477093, 7.38181095, 7.26784858, 7.25278846, 6.74151828,
       7.17324527, 5.90428731, 6.6993297 , 7.45498206, 6.99755487,
       7.5258429 , 6.86306375, 6.60614229, 6.79716195, 6.239697  ,
       7.40480049]
})
df2

,Grupo,NOTAs,Grupo,NOTAS
0,primer grupo,6.724743,segundo grupo,7.065387
1,primer grupo,7.140234,segundo grupo,6.630200
2,primer grupo,7.078668,segundo grupo,6.934210
3,primer grupo,6.656121,segundo grupo,7.265968
4,primer grupo,6.344793,segundo grupo,6.772136
5,primer grupo,7.360375,segundo grupo,6.991462
6,primer grupo,7.482737,segundo grupo,7.485596
7,primer grupo,7.517043,segundo grupo,6.813217
8,primer grupo,7.106631,segundo grupo,7.308404
9,primer grupo,7.543898,segundo grupo,6.887075


In [185]:
df2.describe()

,NOTAS A,NOTAS D
count,56.000000,56.000000
mean,7.079390,6.969426
std,0.388324,0.422703
min,6.285808,5.904287
25%,6.776151,6.749179
50%,7.143248,6.980726
75%,7.361328,7.256083
max,7.812331,8.296559


**evaluacion A**
 el puntaje minimo en la evaluacion A fue de 6.2 y el valor maximo fue de 7.8 una media de 7.0 y una mediana de 7.1 un 25% saco 6.7 y un 75% saco 7.3

**ahora la evaluacion B**
el puntaje minimo fue de 5.9 y el puntaje maximo fue de 8.2
una media de 6.9 y una mediana de 7.2 el 25% saco 6.7 y el 75% saco 7.2

en general a los dos grupos les fue similar pero en el grupo A se nota una nota un poco mayor

In [186]:
from scipy import stats

In [187]:
from scipy.stats import shapiro
shapiro(df["nota"])

ShapiroResult(statistic=np.float64(0.7988683251388914), pvalue=np.float64(0.07932912229256452))

no se rechaza el supuesto de normalidad ya que el valor P no bajo de los 0.05

In [209]:
stats.ttest_rel(df["C"], df["D"])
# profe no se que paso aqui no me funciona ;(

KeyError: 'C'

In [175]:
import os
os.makedirs("comparacion", exist_ok=True)

In [176]:
%%writefile comparacion/pruebat.py

Writing comparacion/pruebat.py


In [177]:
%%writefile comparacion/cor.py

Writing comparacion/cor.py
